#!/usr/bin/env bash
# One-command RuView ESP32 CSI node provisioning.
#
# Everything that can be prepared without the hardware in hand is prepared
# here: wifi credentials, the aggregator address, the flash layout, and the
# flash itself. The operator only has to plug the board in.
#
#   ./provision_node.sh --ssid "HomeWifi" --pass "hunter2"
#   ./provision_node.sh --ssid "HomeWifi" --pass "hunter2" --agg 192.168.1.50
#   ./provision_node.sh --ssid "HomeWifi" --pass "hunter2" --16mb --build
#
# --agg is the PHONE's LAN IP on the sensing WiFi (where the relay listens),
# NOT a Tailscale IP and NOT the VPS. Omit it and it is read from the registry
# the phone populated via bootstrap.sh -- so once the phone has run the
# bootstrap you never have to know or type the address.
#
# --agg-registered  require the registry value, failing if the phone has not
#                   registered yet (never silently fall back to the VPS).
set -euo pipefail

SSID=""; PASS=""; AGG=""; PORT=""
SIZE="4mb"; BUILD=0; SKIP_FLASH=0; AGG_REGISTERED=0
REPO="${REPO:-/root/repos/RuView}"
FW="$REPO/firmware/esp32-csi-node"
BUILD_DIR="$FW/build"

die() { echo "ERROR: $*" >&2; exit 1; }
step() { echo; echo "=== $*"; }

while [ $# -gt 0 ]; do
  case "$1" in
    --ssid) SSID="$2"; shift 2;;
    --pass) PASS="$2"; shift 2;;
    --agg)  AGG="$2";  shift 2;;
    --port) PORT="$2"; shift 2;;
    --16mb) SIZE="16mb"; shift;;
    --4mb)  SIZE="4mb";  shift;;
    --build) BUILD=1; shift;;
    --skip-flash) SKIP_FLASH=1; shift;;
    --agg-registered) AGG_REGISTERED=1; shift;;
    -h|--help) sed -n '2,14p' "$0"; exit 0;;
    *) die "unknown argument: $1";;
  esac
done

[ -n "$SSID" ] || die "--ssid is required"
[ -n "$PASS" ] || die "--pass is required"

# Resolve the aggregator address: explicit --agg wins, else the registry the
# phone wrote, else (unless --agg-registered) the VPS tailnet address.
REGISTRY="${RUVIEW_PHONE_REGISTRY:-/root/ruview/phone_registry.json}"
if [ -z "$AGG" ] && [ -f "$REGISTRY" ]; then
  AGG="$(sed -n 's/.*"lan_ip": "\([0-9.]*\)".*/\1/p' "$REGISTRY" | head -1)"
  [ -n "$AGG" ] && echo "ESP32 target from the phone registry: $AGG"
fi
if [ "$AGG_REGISTERED" = "1" ] && [ -z "$AGG" ]; then
  die "no phone has registered a LAN address yet -- run bootstrap.sh on the phone first."
fi

step "1/5 build target: ESP32-C6, $SIZE flash"
if [ "$BUILD" = "1" ] || [ ! -f "$BUILD_DIR/flash_args" ]; then
  echo "    building in docker (espressif/idf:v5.4)"
  # NOTE: order matters and the upstream RUNBOOK gets it wrong. Each overlay
  # says it layers on top of the previous one, so esp32c6 must come BEFORE
  # 16mb -- otherwise esp32c6's 4MB layout overwrites the 16MB request and you
  # silently get a 4MB image. Verified: the RUNBOOK's documented order yields
  # FLASHSIZE=4MB even when 16mb was requested.
  ORDER="sdkconfig.defaults sdkconfig.defaults.esp32c6"
  [ "$SIZE" = "16mb" ] && ORDER="$ORDER sdkconfig.defaults.16mb"
  MSYS_NO_PATHCONV=1 docker run --rm -v "$FW:/project" -w /project espressif/idf:v5.4 bash -c "
    cat $ORDER > sdkconfig.defaults.build
    SDKCONFIG_DEFAULTS='sdkconfig.defaults.build' idf.py set-target esp32c6
    SDKCONFIG_DEFAULTS='sdkconfig.defaults.build' idf.py build" | tail -25
else
  echo "    reusing existing build in $BUILD_DIR (pass --build to rebuild)"
fi

step "2/5 verifying the build matches the requested flash size"
GOT_SIZE="$(sed -n 's/^CONFIG_ESPTOOLPY_FLASHSIZE="\(.*\)"$/\1/p' "$FW/sdkconfig")"
GOT_PART="$(sed -n 's/^CONFIG_PARTITION_TABLE_CUSTOM_FILENAME="\(.*\)"$/\1/p' "$FW/sdkconfig")"
WANT_SIZE="$(echo "$SIZE" | tr a-z A-Z)"
echo "    built: FLASHSIZE=$GOT_SIZE partition=$GOT_PART"
[ "$GOT_SIZE" = "$WANT_SIZE" ] || die "built for $GOT_SIZE but $WANT_SIZE requested - re-run with --build --$SIZE"
# These three are the runbook's non-negotiables: a silent mismatch here bricks
# OTA rollback or repartitions NVS under a live node.
for k in CONFIG_IDF_TARGET CONFIG_BOOTLOADER_APP_ROLLBACK_ENABLE CONFIG_ESP_WIFI_CSI_ENABLED; do
  v="$(sed -n "s/^$k=//p" "$FW/sdkconfig")"
  echo "    $k=$v"
  [ -n "$v" ] || die "$k missing from sdkconfig"
done

step "3/5 writing site credentials"
cat > "$FW/sdkconfig.defaults.site" <<EOF
# Generated by provision_node.sh - site credentials, gitignored, never commit.
CONFIG_CSI_WIFI_SSID="$SSID"
CONFIG_CSI_WIFI_PASSWORD="$PASS"
CONFIG_CSI_TARGET_ADDR="${AGG:-100.126.180.47}"
CONFIG_CSI_TARGET_PORT=5005
EOF
chmod 600 "$FW/sdkconfig.defaults.site"
echo "    wrote $FW/sdkconfig.defaults.site -> ${AGG:-100.126.180.47}:5005"

step "4/5 serial port"
if [ -z "$PORT" ]; then
  PORT="$(ls /dev/ttyUSB0 /dev/ttyACM0 2>/dev/null | head -1 || true)"
  [ -n "$PORT" ] || die "no serial device. Plug the board in (appears as /dev/ttyUSB0 or /dev/ttyACM0) and re-run, or pass --port."
fi
echo "    port: $PORT"

step "5/5 flash"
if [ "$SKIP_FLASH" = "1" ]; then
  echo "    skipped (--skip-flash)"
else
  # Offsets come from the build's own flash_args, never hand-copied. Both the
  # 4MB and 16MB tables currently place the app at 0x20000, but they are not
  # guaranteed to, and --flash_size in those args is what esptool needs per
  # board. Reading the file means a partition-table change upstream cannot
  # silently flash the wrong layout.
  ARGS="$(sed 's|^|'"$BUILD_DIR"'/|' "$BUILD_DIR/flash_args")"
  echo "    esptool $ARGS"
  # shellcheck disable=SC2086
  python3 -m esptool --chip esp32c6 -b 460800 -p "$PORT" write_flash $ARGS
  echo
  echo "    board will reboot; watch the boot log with:"
  echo "      python3 -m serial.tools.miniterm -b 115200 $PORT"
fi

cat <<EOF

Next:
  1. On the phone (Termux):  ip -4 addr show wlan0   -> that LAN IP is what the
     node is now configured to send to.
  2. On the phone:           ~/ruview/start-relay.sh
  3. Confirm the server sees a live node:
       curl -s http://100.126.180.47:3000/health
     source must read 'esp32' -- not 'simulated', not 'esp32:offline'.
EOF
